// quest_data.js - Ver 52.0 (All Regions Complete)

// --- REGION REWARDS (地域制覇報酬) ---
const REGION_REWARDS = {
    // 表日本
    "east": { name: "伊達政宗", rarity: "R" },
    "central": { name: "織田信長", rarity: "R" },
    "west": { name: "毛利元就", rarity: "R" },
    "山城": { name: "三好長慶", rarity: "R" },
    "河内": { name: "細川ガラシャ", rarity: "R" },
    "越前": { name: "朝倉宗滴", rarity: "R" },
    "近江": { name: "浅井長政", rarity: "R" },
    "紀伊・大和": { name: "松永久秀", rarity: "R" },
    "三河": { name: "酒井忠次", rarity: "SR" },
    "安芸・山陽": { name: "小早川隆景", rarity: "SR" },
    "薩摩": { name: "島津歳久", rarity: "SR" },
    "越後": { name: "直江景綱", rarity: "SR" },
    "土佐・南海": { name: "長宗我部信親", rarity: "SR" },
    "肥前・肥後": { name: "鍋島直茂", rarity: "SR" },
    "尾張・美濃": { name: "森蘭丸", rarity: "R" },
    "豊前・豊後": { name: "立花誾千代", rarity: "SR" },
    "陸奥・出羽": { name: "片倉小十郎", rarity: "SR" },
    "駿河": { name: "太原雪斎", rarity: "SR" },
    "上野・武蔵": { name: "北条氏康", rarity: "R" },
    "信濃・甲斐": { name: "山本勘助", rarity: "SR" },
    "摂津・備前": { name: "雑賀孫市", rarity: "SR" },
    
    // 裏日本
    "裏越後": { name: "上杉四天王", rarity: "SP" },
    "裏信濃・甲斐": { name: "武田四名臣", rarity: "SP" },
    "裏三河": { name: "徳川四天王", rarity: "SP" },
    "裏薩摩": { name: "島津四兄弟", rarity: "SP" },
    "裏陸奥・出羽": { name: "独眼竜両翼", rarity: "SP" }
};

// 地域マッピング
const REGION_MAP = {
    "east": ["陸奥", "出羽", "越後", "信濃", "上野", "下野", "常陸", "武蔵", "下総", "上総", "安房", "相模", "甲斐", "駿河", "伊豆"],
    "central": ["越中", "能登", "加賀", "越前", "美濃", "飛騨", "尾張", "三河", "遠江", "近江", "伊勢", "志摩", "山城", "大和", "紀伊", "河内", "和泉", "摂津", "丹波", "丹後", "但馬", "播磨"],
    "west": ["因幡", "伯耆", "出雲", "石見", "隠岐", "美作", "備前", "備中", "備後", "安芸", "周防", "長門", "淡路", "阿波", "讃岐", "伊予", "土佐", "筑前", "筑後", "豊前", "豊後", "肥前", "肥後", "日向", "大隅", "薩摩"],
    "ura": ["裏越後", "裏信濃・甲斐", "裏三河", "裏安芸・山陽", "裏薩摩", "裏陸奥・出羽", "裏上野・武蔵", "裏土佐・南海", "裏豊前・豊後", "裏肥前・肥後", "裏摂津・備前", "裏駿河", "裏紀伊・大和", "裏近江", "裏越前", "裏河内", "裏山城"]
};

// --- QUEST DATA ---
const QUEST_DATA = [
    { id: 101, region: "尾張・美濃", name: "稲生", diff: 1, money: 20, food: 4, boss_r: "R", type: "足軽", terrain: "平原", interference: [], s_cond: "R織田信長", s_reward_char: "R織田信長",
      random_rewards: [{"type": "money", "val": 2}] },
    { id: 102, region: "尾張・美濃", name: "浮野・岩倉城", diff: 1, money: 30, food: 6, boss_r: "R", type: "足軽", terrain: "城郭", interference: [], s_cond: "R織田信長", s_reward_char: "R織田信長",
      random_rewards: [{"type": "money", "val": 3}] },
    { id: 103, region: "尾張・美濃", name: "桶狭間", diff: 1, money: 45, food: 9, boss_r: "R", type: "弓兵", terrain: "平原", interference: ["悪天候"], s_cond: "R織田信長", s_reward_char: "R織田信長",
      unique_enemies: ["C今川氏真", "R松平元康"],
      random_rewards: [{"type": "money", "val": 10}, {"type": "char", "name": "R松平元康", "weight": 5}] },
    { id: 104, region: "尾張・美濃", name: "小牧・長久手", diff: 1, money: 60, food: 12, boss_r: "R", type: "鉄砲", terrain: "平原", interference: ["悪天候"], s_cond: "R羽柴秀吉", s_reward_char: "C木下藤吉郎",
      unique_enemies: ["R徳川家康", "R榊原康政", "R本多忠勝"],
      random_rewards: [{"type": "money", "val": 20}, {"type": "char", "name": "R本多忠勝", "weight": 5}] },
    { id: 105, region: "山城", name: "比叡山", diff: 2, money: 45, food: 9, boss_r: "C", type: "足軽", terrain: "山岳", interference: [], s_cond: "C明智光秀", s_reward_char: "C明智光秀",
      unique_enemies: ["C山岡景友", "C和田惟政"],
      random_rewards: [{"type": "money", "val": 10}] },
    { id: 106, region: "山城", name: "山崎", diff: 2, money: 60, food: 12, boss_r: "C", type: "足軽", terrain: "平原", interference: [], s_cond: "R羽柴秀吉", s_reward_char: "C池田恒興",
      unique_enemies: ["C高山右近", "C池田恒興", "C中川清秀"],
      random_rewards: [{"type": "money", "val": 20}, {"type": "char", "name": "R池田恒興", "weight": 5}] },
    { id: 107, region: "山城", name: "二条城", diff: 2, money: 75, food: 15, boss_r: "R", type: "足軽", terrain: "城郭", interference: [], s_cond: "R織田信長", s_reward_char: "R三好長慶",
      unique_enemies: ["C三好政康", "C岩成友通", "C三好長逸", "R三好長慶"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "R三好長慶", "weight": 5}] },
    { id: 108, region: "山城", name: "将軍地蔵山城", diff: 2, money: 100, food: 20, boss_r: "R", type: "足軽", terrain: "山岳", interference: [], s_cond: "R三好長慶", s_reward_char: "R三好長慶",
      unique_enemies: ["C三好長逸", "C岩成友通", "C三好政康", "R松永久秀", "SR三好長慶"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 109, region: "越前", name: "九頭竜川", diff: 4, money: 120, food: 24, boss_r: "R", type: "騎馬", terrain: "河川", interference: ["悪天候"], s_cond: "R朝倉宗滴", s_reward_char: "R朝倉宗滴",
      random_rewards: [{"type": "money", "val": 4}] },
    { id: 110, region: "越前", name: "姉川", diff: 4, money: 150, food: 30, boss_r: "C", type: "騎馬", terrain: "河川", interference: ["悪天候"], s_cond: "R織田信長", s_reward_char: "R磯野員昌",
      unique_enemies: ["C磯野員昌", "C遠藤直経", "C阿閉貞征", "C赤尾清綱", "C雨森弥兵衛", "R海北綱親"],
      random_rewards: [{"type": "money", "val": 10}, {"type": "char", "name": "R磯野員昌", "weight": 5}] },
    { id: 111, region: "越前", name: "金ヶ崎", diff: 4, money: 165, food: 33, boss_r: "R", type: "騎馬", terrain: "山岳", interference: ["悪天候"], s_cond: "C木下藤吉郎", s_reward_char: "R浅井長政",
      unique_enemies: ["C赤尾清綱", "C雨森弥兵衛", "R海北綱親", "R浅井長政"],
      random_rewards: [{"type": "money", "val": 20}, {"type": "char", "name": "R浅井長政", "weight": 5}] },
    { id: 112, region: "越前", name: "一乗谷城", diff: 4, money: 180, food: 36, boss_r: "C", type: "騎馬", terrain: "城郭", interference: ["悪天候"], s_cond: "R織田信長", s_reward_char: "C朝倉義景",
      unique_enemies: ["C朝倉義景", "R朝倉景鏡"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "C朝倉義景", "weight": 5}] },
    { id: 113, region: "越前", name: "刀根坂", diff: 4, money: 150, food: 30, boss_r: "C", type: "騎馬", terrain: "山岳", interference: ["悪天候"], s_cond: "R織田信長", s_reward_char: "R朝倉宗滴",
      unique_enemies: ["R朝倉宗滴", "SR朝倉宗滴"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 114, region: "紀伊・大和", name: "雑賀川", diff: 6, money: 150, food: 30, boss_r: "R", type: "足軽", terrain: "河川", interference: ["計略"], s_cond: "R雑賀孫市", s_reward_char: "R高山右近",
      unique_enemies: ["R高山右近"],
      random_rewards: [{"type": "money", "val": 20}] },
    { id: 115, region: "紀伊・大和", name: "信貴山城", diff: 6, money: 225, food: 45, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["計略"], s_cond: "R羽柴秀吉", s_reward_char: "C筒井順慶",
      unique_enemies: ["C筒井順慶"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "C筒井順慶", "weight": 5}] },
    { id: 116, region: "紀伊・大和", name: "多聞山城", diff: 6, money: 290, food: 58, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["足止め罠", "計略"], s_cond: "R織田信長", s_reward_char: "R松永久秀",
      unique_enemies: ["R松永久秀", "SR松永久秀"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 117, region: "駿河", name: "小豆坂", diff: 6, money: 150, food: 30, boss_r: "C", type: "弓兵", terrain: "平原", interference: ["足止め罠"], s_cond: "C今川義元", s_reward_char: "C今川義元",
      unique_enemies: ["朝比奈泰朝"],
      random_rewards: [{"type": "money", "val": 2}] },
    { id: 118, region: "駿河", name: "高天神城", diff: 6, money: 225, food: 45, boss_r: "C", type: "弓兵", terrain: "城郭", interference: ["足止め罠"], s_cond: "R徳川家康", s_reward_char: "R岡部元信",
      unique_enemies: ["R岡部元信"],
      random_rewards: [{"type": "money", "val": 20}, {"type": "char", "name": "R岡部元信", "weight": 5}] },
    { id: 119, region: "駿河", name: "駿府城", diff: 6, money: 270, food: 54, boss_r: "C", type: "弓兵", terrain: "城郭", interference: ["足止め罠"], s_cond: "R徳川家康", s_reward_char: "R寿桂尼",
      unique_enemies: ["C今川氏真", "R寿桂尼"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "R寿桂尼", "weight": 5}] },
    { id: 120, region: "駿河", name: "安祥城", diff: 6, money: 250, food: 50, boss_r: "R", type: "弓兵", terrain: "平原", interference: ["奇襲"], s_cond: "R織田信長", s_reward_char: "SR太原雪斎",
      unique_enemies: ["R太原雪斎", "SR太原雪斎"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 121, region: "陸奥・出羽", name: "摺上原", diff: 8, money: 240, food: 48, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["悪天候", "奇襲"], s_cond: "R伊達政宗", s_reward_char: "R伊達政宗",
      unique_enemies: ["R留守政景", "R白石宗実"],
      random_rewards: [{"type": "money", "val": 30}] },
    { id: 122, region: "陸奥・出羽", name: "長谷堂城", diff: 8, money: 270, food: 54, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["悪天候", "奇襲"], s_cond: "R直江兼続", s_reward_char: "R伊達成実",
      unique_enemies: ["R白石宗実", "R伊達成実"],
      random_rewards: [{"type": "money", "val": 40}, {"type": "char", "name": "R伊達成実", "weight": 5}] },
    { id: 123, region: "陸奥・出羽", name: "小手森城", diff: 8, money: 400, food: 80, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["悪天候", "奇襲"], s_cond: "R伊達政宗", s_reward_char: "R義姫",
      unique_enemies: ["R義姫"],
      random_rewards: [{"type": "money", "val": 50}, {"type": "char", "name": "R義姫", "weight": 5}] },
    { id: 124, region: "陸奥・出羽", name: "米沢城", diff: 8, money: 440, food: 88, boss_r: "SR", type: "騎馬", terrain: "城郭", interference: ["悪天候", "奇襲"], s_cond: "R直江兼続", s_reward_char: "R片倉小十郎",
      unique_enemies: ["R片倉小十郎", "R伊達政宗", "SR伊達政宗"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R片倉小十郎", "weight": 5}] },
    { id: 125, region: "陸奥・出羽", name: "青葉城", diff: 8, money: 600, food: 120, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["悪天候", "奇襲"], s_cond: "R伊達政宗", s_reward_char: "SR片倉小十郎",
      unique_enemies: ["SR片倉小十郎"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 126, region: "上野・武蔵", name: "小沢原", diff: 8, money: 120, food: 24, boss_r: "R", type: "足軽", terrain: "平原", interference: ["足止め罠"], s_cond: "R北条氏康", s_reward_char: "R北条氏康",
      unique_enemies: ["R松田憲秀"],
      random_rewards: [{"type": "money", "val": 4}] },
    { id: 127, region: "上野・武蔵", name: "鉢形城", diff: 8, money: 140, food: 28, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "C前田利家", s_reward_char: "R北条氏邦",
      unique_enemies: ["R北条氏邦"],
      random_rewards: [{"type": "money", "val": 20}, {"type": "char", "name": "R北条氏邦", "weight": 5}] },
    { id: 128, region: "上野・武蔵", name: "国府台", diff: 8, money: 240, food: 48, boss_r: "R", type: "忍者", terrain: "平原", interference: ["足止め罠"], s_cond: "R北条氏康", s_reward_char: "R北条綱成",
      unique_enemies: ["R北条綱成"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "R北条綱成", "weight": 5}] },
    { id: 129, region: "上野・武蔵", name: "河越城", diff: 8, money: 270, food: 54, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "R北条氏康", s_reward_char: "R北条早雲",
      unique_enemies: ["R北条早雲", "R風魔小太郎"],
      random_rewards: [{"type": "money", "val": 40}, {"type": "char", "name": "R北条早雲", "weight": 5}] },
    { id: 130, region: "上野・武蔵", name: "小田原城", diff: 8, money: 750, food: 150, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "UR豊太閤秀吉", s_reward_char: "R北条氏康",
      unique_enemies: ["R北条氏康", "SR北条氏康"],
      random_rewards: [{"type": "money", "val": 60}] },
    { id: 131, region: "土佐・南海", name: "一宮城", diff: 8, money: 180, food: 36, boss_r: "N", type: "水兵", terrain: "城郭", interference: ["布陣失敗", "傷病"], s_cond: "R長宗我部元親", s_reward_char: "R長宗我部元親",
      random_rewards: [{"type": "money", "val": 20}] },
    { id: 132, region: "土佐・南海", name: "引田", diff: 8, money: 210, food: 42, boss_r: "C", type: "水兵", terrain: "海戦", interference: ["布陣失敗", "傷病"], s_cond: "R長宗我部元親", s_reward_char: "C吉良親貞",
      unique_enemies: ["C吉良親貞", "R福留儀重"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "C吉良親貞", "weight": 5}] },
    { id: 133, region: "土佐・南海", name: "天霧城", diff: 8, money: 360, food: 72, boss_r: "SR", type: "水兵", terrain: "城郭", interference: ["布陣失敗", "傷病"], s_cond: "R長宗我部元親", s_reward_char: "R香宗我部親泰",
      unique_enemies: ["R香宗我部親泰", "R吉田重俊"],
      random_rewards: [{"type": "money", "val": 40}, {"type": "char", "name": "R香宗我部親泰", "weight": 5}] },
    { id: 134, region: "土佐・南海", name: "湯築城", diff: 8, money: 240, food: 48, boss_r: "SR", type: "水兵", terrain: "城郭", interference: ["布陣失敗", "傷病"], s_cond: "R小早川隆景", s_reward_char: "R長宗我部信親",
      unique_enemies: ["R長宗我部信親", "SR長宗我部信親"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R長宗我部信親", "weight": 5}] },
    { id: 135, region: "土佐・南海", name: "白地城", diff: 8, money: 500, food: 100, boss_r: "SSR", type: "水兵", terrain: "城郭", interference: ["布陣失敗", "傷病"], s_cond: "R長宗我部元親", s_reward_char: "SR長宗我部信親",
      unique_enemies: ["SR長宗我部信親"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 136, region: "三河", name: "三方ヶ原", diff: 9, money: 480, food: 96, boss_r: "R", type: "弓兵", terrain: "平原", interference: ["奇襲", "布陣失敗"], s_cond: "R武田信玄", s_reward_char: "R武田信玄",
      unique_enemies: ["R井伊直政", "R鳥居元忠", "R酒井忠次", "R榊原康政"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 137, region: "三河", name: "長篠", diff: 9, money: 560, food: 112, boss_r: "SR", type: "騎馬", terrain: "平原", interference: ["奇襲", "布陣失敗"], s_cond: "R織田信長", s_reward_char: "R本多忠勝",
      unique_enemies: ["R本多忠勝", "R榊原康政", "R井伊直政", "R服部半蔵"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R本多忠勝", "weight": 5}] },
    { id: 138, region: "三河", name: "浜松城", diff: 9, money: 750, food: 150, boss_r: "SR", type: "騎馬", terrain: "城郭", interference: ["奇襲", "布陣失敗"], s_cond: "R徳川家康", s_reward_char: "SR酒井忠次",
      unique_enemies: ["R徳川家康", "SR徳川家康", "R酒井忠次", "SR酒井忠次"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 139, region: "安芸・山陽", name: "三木城", diff: 9, money: 300, food: 60, boss_r: "C", type: "水兵", terrain: "城郭", interference: ["計略", "奇襲", "傷病"], s_cond: "R羽柴秀吉", s_reward_char: "R羽柴秀吉",
      unique_enemies: ["C清水宗治", "R安国寺恵瓊"],
      random_rewards: [{"type": "money", "val": 20}] },
    { id: 140, region: "安芸・山陽", name: "鳥取城", diff: 9, money: 330, food: 66, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["計略", "奇襲", "傷病"], s_cond: "R羽柴秀吉", s_reward_char: "C毛利隆元",
      unique_enemies: ["C毛利隆元", "R吉川元春"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "char", "name": "C毛利隆元", "weight": 5}] },
    { id: 141, region: "安芸・山陽", name: "有田城", diff: 9, money: 480, food: 96, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["計略", "奇襲", "傷病"], s_cond: "R毛利元就", s_reward_char: "R吉川元春",
      unique_enemies: ["R吉川元春", "R村上武吉"],
      random_rewards: [{"type": "money", "val": 40}, {"type": "char", "name": "R吉川元春", "weight": 5}] },
    { id: 142, region: "安芸・山陽", name: "厳島", diff: 9, money: 520, food: 104, boss_r: "SR", type: "水兵", terrain: "海戦", interference: ["計略", "奇襲", "傷病"], s_cond: "R毛利元就", s_reward_char: "SR小早川隆景",
      unique_enemies: ["SR小早川隆景", "R村上武吉"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "SR小早川隆景", "weight": 5}] },
    { id: 143, region: "安芸・山陽", name: "吉田郡山城", diff: 9, money: 700, food: 140, boss_r: "SSR", type: "弓兵", terrain: "城郭", interference: ["計略", "奇襲", "傷病"], s_cond: "R毛利元就", s_reward_char: "SR小早川隆景",
      unique_enemies: ["R毛利元就", "SR毛利元就"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 144, region: "薩摩", name: "平佐城", diff: 9, money: 240, food: 48, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["奇襲", "計略"], s_cond: "R小西行長", s_reward_char: "R小西行長",
      unique_enemies: ["C山田有信", "R川上久朗", "R島津家久", "SR島津歳久"],
      random_rewards: [{"type": "money", "val": 30}] },
    { id: 145, region: "薩摩", name: "沖田畷", diff: 9, money: 270, food: 54, boss_r: "R", type: "鉄砲", terrain: "湿地", interference: ["奇襲", "計略"], s_cond: "R島津家久", s_reward_char: "R島津家久",
      unique_enemies: ["R島津家久", "R新納忠元"],
      random_rewards: [{"type": "money", "val": 40}, {"type": "char", "name": "R島津家久", "weight": 5}] },
    { id: 146, region: "薩摩", name: "耳川", diff: 9, money: 400, food: 80, boss_r: "R", type: "足軽", terrain: "河川", interference: ["奇襲", "計略"], s_cond: "R島津家久", s_reward_char: "R島津歳久",
      unique_enemies: ["R島津歳久", "R川上久朗", "C鎌田政年"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R島津歳久", "weight": 5}] },
    { id: 147, region: "薩摩", name: "内城", diff: 9, money: 550, food: 110, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["奇襲", "計略"], s_cond: "R島津義久", s_reward_char: "SR島津歳久",
      unique_enemies: ["R島津義久", "SR島津義久"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 148, region: "信濃・甲斐", name: "上田原", diff: 10, money: 300, food: 60, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["奇襲", "悪天候", "計略", "足止め罠"], s_cond: "R真田幸隆", s_reward_char: "R真田幸隆",
      unique_enemies: ["R内藤昌豊", "R山本勘助"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 149, region: "信濃・甲斐", name: "上田城", diff: 10, money: 640, food: 128, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["奇襲", "悪天候", "計略", "足止め罠"], s_cond: "R真田昌幸", s_reward_char: "R高坂昌信",
      unique_enemies: ["R高坂昌信", "R武田信繁", "R真田幸隆"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R高坂昌信", "weight": 5}] },
    { id: 150, region: "信濃・甲斐", name: "川中島", diff: 10, money: 680, food: 136, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["奇襲", "悪天候", "計略", "足止め罠"], s_cond: "R武田信玄", s_reward_char: "R馬場信春",
      unique_enemies: ["R馬場信春", "R山県昌景", "R山本勘助"],
      random_rewards: [{"type": "money", "val": 80}, {"type": "char", "name": "R馬場信春", "weight": 5}] },
    { id: 151, region: "信濃・甲斐", name: "躑躅ヶ崎館", diff: 10, money: 900, food: 180, boss_r: "SSR", type: "騎馬", terrain: "城郭", interference: ["奇襲", "悪天候", "計略", "傷病"], s_cond: "R武田信玄", s_reward_char: "SR山本勘助",
      unique_enemies: ["R武田信玄", "SR武田信玄"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 152, region: "越後", name: "尻垂坂", diff: 10, money: 300, food: 60, boss_r: "R", type: "足軽", terrain: "平原", interference: ["奇襲", "悪天候", "計略", "足止め罠", "傷病"], s_cond: "R上杉謙信", s_reward_char: "R上杉謙信",
      unique_enemies: ["R甘粕景持"],
      random_rewards: [{"type": "money", "val": 40}] },
    { id: 153, region: "越後", name: "七尾城", diff: 10, money: 480, food: 96, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["奇襲", "悪天候", "計略", "足止め罠"], s_cond: "R上杉謙信", s_reward_char: "R柿崎景家",
      unique_enemies: ["R柿崎景家", "R上杉景信"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R柿崎景家", "weight": 5}] },
    { id: 154, region: "越後", name: "手取川", diff: 10, money: 680, food: 136, boss_r: "R", type: "騎馬", terrain: "河川", interference: ["奇襲", "悪天候", "計略", "足止め罠", "傷病"], s_cond: "R上杉謙信", s_reward_char: "R直江景綱",
      unique_enemies: ["R直江景綱", "R宇佐美定満", "R甘粕景持"],
      random_rewards: [{"type": "money", "val": 80}, {"type": "char", "name": "R直江景綱", "weight": 5}] },
    { id: 155, region: "越後", name: "春日山城", diff: 10, money: 900, food: 180, boss_r: "SSR", type: "騎馬", terrain: "城郭", interference: ["奇襲", "悪天候", "計略", "足止め罠", "傷病"], s_cond: "R上杉謙信", s_reward_char: "SR直江景綱",
      unique_enemies: ["R上杉謙信", "SR上杉謙信"],
      random_rewards: [{"type": "money", "val": 100}] },
    { id: 156, region: "イベント", name: "☆大坂の役", diff: 8, money: 400, food: 111, boss_r: "SSR", type: "騎馬", terrain: "城郭", interference: ["布陣失敗", "足止め罠", "傷病"], s_cond: "UR征夷大将軍家康", s_reward_char: "UR征夷大将軍家康",
      unique_enemies: ["R長宗我部盛親", "R後藤又兵衛", "R明石全登", "SR毛利勝永", "R猿飛佐助", "R塙団右衛門", "SR霧隠才蔵", "SR千姫"],
      random_rewards: [{"type": "money", "val": 80}] },
    { id: 157, region: "イベント", name: "☆安土城", diff: 8, money: 400, food: 80, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["布陣失敗"], s_cond: "R織田信長", s_reward_char: "R織田信長",
      unique_enemies: ["SR前田慶次", "Rお市"],
      random_rewards: [{"type": "money", "val": 80}, {"type": "item", "name": "kokoro", "val": 1}] },
    { id: 158, region: "イベント", name: "☆下田城", diff: 8, money: 415, food: 83, boss_r: "C", type: "弓兵", terrain: "城郭", interference: ["足止め罠", "傷病"], s_cond: "R徳川家康", s_reward_char: "R徳川家康",
      unique_enemies: ["R脇坂安治", "R加藤嘉明", "R糟屋武則", "R片桐且元", "R平野長泰"],
      random_rewards: [{"type": "money", "val": 83}] },
    { id: 159, region: "イベント", name: "☆江戸城", diff: 10, money: 675, food: 135, boss_r: "UR", type: "足軽", terrain: "城郭", interference: ["奇襲", "布陣失敗"], s_cond: "SR酒井忠次", s_reward_char: "SR酒井忠次",
      unique_enemies: ["R本多正信", "SR服部半蔵", "SR本多忠勝", "SR井伊直政", "SR榊原康政", "SR酒井忠次", "SR柳生石舟斎", "R南光坊天海"],
      random_rewards: [{"type": "money", "val": 135}] },
    { id: 160, region: "イベント", name: "☆駿河湾海戦", diff: 8, money: 365, food: 73, boss_r: "R", type: "騎馬", terrain: "海戦", interference: ["悪天候", "布陣失敗"], s_cond: "R九鬼嘉隆", s_reward_char: "R九鬼嘉隆",
      unique_enemies: ["R北条綱成", "R北条早雲", "R村上武吉", "C清水宗治", "R向井正綱", "SR小早川隆景", "C三浦按針", "C板部岡江雪斎", "R九鬼嘉隆"],
      random_rewards: [{"type": "money", "val": 73}] },
    { id: 161, region: "イベント", name: "☆九度山", diff: 8, money: 450, food: 90, boss_r: "SR", type: "鉄砲", terrain: "山岳", interference: ["奇襲", "足止め罠"], s_cond: "SR真田信之", s_reward_char: "SR真田信之",
      unique_enemies: ["R真田信之", "R真田幸村", "R真田昌幸", "R真田幸隆", "R猿飛佐助", "R小松姫", "R霧隠才蔵", "C真田大助", "C三好清海", "C三好伊三", "C根津甚八", "C穴山小助", "C由利鎌之助", "C海野六郎", "C望月六郎", "C筧十蔵"],
      random_rewards: [{"type": "money", "val": 90}] },
    { id: 162, region: "イベント", name: "☆石橋山", diff: 8, money: 475, food: 95, boss_r: "SR", type: "忍者", terrain: "山岳", interference: ["奇襲", "布陣失敗"], s_cond: "R雑賀孫市", s_reward_char: "R雑賀孫市",
      unique_enemies: ["R加藤段蔵", "R望月千代女", "R石川五右衛門", "R風魔小太郎", "R服部半蔵", "R百地三太夫", "R猿飛佐助", "SR霧隠才蔵", "R果心居士", "R柳生石舟斎"],
      random_rewards: [{"type": "money", "val": 95}] },
    { id: 163, region: "イベント", name: "☆伊賀の里", diff: 7, money: 300, food: 60, boss_r: "SR", type: "忍者", terrain: "山岳", interference: ["奇襲", "傷病"], s_cond: "R徳川家康", s_reward_char: "R徳川家康",
      unique_enemies: ["SR服部半蔵", "R石川五右衛門", "R百地三太夫"],
      random_rewards: [{"type": "money", "val": 60}] },
    { id: 164, region: "イベント", name: "☆巌流島", diff: 8, money: 450, food: 90, boss_r: "SR", type: "足軽", terrain: "海戦", interference: ["奇襲", "足止め罠", "悪天候"], s_cond: "SR宮本武蔵", s_reward_char: "SR宮本武蔵",
      unique_enemies: ["R柳生石舟斎", "R宝蔵院胤栄", "R塚原卜伝", "R上泉信綱", "R伊藤一刀斎", "R佐々木小次郎", "R富田勢源", "SR宮本武蔵"],
      random_rewards: [{"type": "money", "val": 90}] },
    { id: 165, region: "イベント", name: "☆石見銀山", diff: 8, money: 450, food: 90, boss_r: "R", type: "足軽", terrain: "山岳", interference: ["足止め罠", "傷病"], s_cond: "R毛利元就", s_reward_char: "R毛利元就",
      unique_enemies: ["SR山中鹿之助", "R尼子経久", "R三好長慶", "R細川幽斎", "R松永久秀", "C山岡景友", "C和田惟政", "SR足利義昭"],
      random_rewards: [{"type": "money", "val": 90}] },
    { id: 166, region: "イベント", name: "☆南蛮渡来船", diff: 5, money: 175, food: 35, boss_r: "C", type: "水兵", terrain: "海戦", interference: ["悪天候"], s_cond: "Cザビエル", s_reward_char: "Cルイス・フロイス",
      unique_enemies: ["C弥助", "R大友宗麟", "C支倉常長", "Cルイス・フロイス", "R細川ガラシャ", "R高山右近", "Cヴァリニャーノ", "R小西行長", "Cザビエル"],
      random_rewards: [{"type": "money", "val": 10}, {"type": "char", "name": "R小西行長", "weight": 5}] },
    { id: 167, region: "イベント", name: "☆佐渡金山", diff: 8, money: 600, food: 77, boss_r: "SR", type: "足軽", terrain: "山岳", interference: ["傷病", "足止め罠"], s_cond: "UR豊太閤秀吉", s_reward_char: "SR宇佐美定満",
      cond_desc: "豊臣家 武将1名以上", entry_cond: {"type": "clan", "value": "豊臣家", "count": 1, "op": ">="},
      unique_enemies: ["R柿崎景家", "R甘粕景持", "R長野業正", "R直江景綱", "R斎藤朝信", "R上杉景信", "SR宇佐美定満", "SR直江景綱"],
      random_rewards: [{"type": "money", "val": 120}, {"type": "char", "name": "SR宇佐美定満", "weight": 5}] },
    { id: 168, region: "イベント", name: "☆伊勢湾の海賊", diff: 6, money: 300, food: 60, boss_r: "R", type: "水兵", terrain: "海戦", interference: ["奇襲"], s_cond: "SSR武田信玄", s_reward_char: "SSR武田信玄",
      unique_enemies: ["R九鬼嘉隆", "R村上武吉", "R向井正綱"],
      random_rewards: [{"type": "money", "val": 60}, {"type": "char", "name": "R九鬼嘉隆", "weight": 5}] },
    { id: 169, region: "イベント", name: "☆関ヶ原(対東軍)", diff: 10, money: 6000, food: 260, boss_r: "R", type: "足軽", terrain: "平原", interference: ["悪天候", "奇襲", "布陣失敗"], s_cond: "R石田三成", s_reward_char: "R石田三成",
      unique_enemies: ["R徳川家康", "R福島正則", "R黒田長政", "R本多忠勝", "R井伊直政", "R細川忠興", "R加藤嘉明", "R山内一豊", "R藤堂高虎", "R浅野幸長", "R京極高知", "R寺沢広高", "C田中吉政", "R古田織部", "R伊達正宗", "R最上義光", "R前田利長"],
      random_rewards: [{"type": "money", "val": 260}] },
    { id: 170, region: "イベント", name: "☆本能寺の変", diff: 10, money: 6000, food: 240, boss_r: "UR", type: "鉄砲", terrain: "城郭", interference: ["奇襲"], s_cond: "SSR明智光秀", s_reward_char: "SSR明智光秀",
      unique_enemies: ["SSR明智光秀", "R明智秀満", "R斎藤利三", "C溝尾茂朝", "C安田国継"],
      random_rewards: [{"type": "money", "val": 240}] },
    { id: 171, region: "イベント", name: "☆関ヶ原(対西軍)", diff: 10, money: 6000, food: 260, boss_r: "R", type: "足軽", terrain: "平原", interference: ["悪天候", "奇襲", "布陣失敗"], s_cond: "R徳川家康", s_reward_char: "R徳川家康",
      unique_enemies: ["R島左近", "R宇喜多秀家", "R大谷吉継", "R小西行長", "R石田三成", "R島津義弘", "R島津豊久", "R長宗我部盛親", "R毛利秀元", "R吉川広家", "R安国寺恵瓊", "R小早川秀秋", "C脇坂安治", "C小川祐忠", "C朽木元綱", "C赤座直保"],
      random_rewards: [{"type": "money", "val": 260}] },
    { id: 172, region: "イベント", name: "☆鳥羽・伏見", diff: 9, money: 2246, food: 90, boss_r: "SSR", type: "足軽", terrain: "平原", interference: ["奇襲", "布陣失敗", "悪天候", "傷病", "足止め罠"], s_cond: "C木下藤吉郎", s_reward_char: "SR出雲阿国",
      cond_desc: "多種妨害注意!",
      unique_enemies: ["SR山中鹿之助", "R尼子経久", "R三好長慶", "R細川幽斎", "R松永久秀", "C山岡景友", "C和田惟政", "SR足利義昭", "R海北綱親", "R風魔小太郎", "R濃姫", "R森蘭丸", "R服部半蔵"],
      unique_treasures: ["新田肩衝", "松本茄子", "三日月", "松島", "松花", "橋立", "平蜘蛛", "乙御前釜", "貨狄", "十二支釜", "大曽呂利", "弱法師", "浅間", "袴腰", "村正"],
      random_rewards: [{"type": "money", "val": 30}, {"type": "money", "val": 1123}, {"type": "money", "val": 2246}, {"type": "item", "name": "kokoro", "val": 10}, {"type": "item", "name": "kokoro", "val": 20}, {"type": "char", "name": "SR出雲阿国", "weight": 5}, {"type": "char", "name": "SR足利義昭", "weight": 5}, {"type": "char", "name": "SR十河一存", "weight": 5}] },
    { id: 173, region: "裏越後", name: "三条城", diff: 11, money: 600, food: 120, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["悪天候"], s_cond: "R上杉景勝", s_reward_char: "R上杉景勝",
      cond_desc: "姫武将1名以下", entry_cond: {"type": "gender_count", "value": "female", "count": 1, "op": "<="},
      unique_enemies: ["R色部勝長", "R直江兼続", "R上杉景勝", "R直江景綱", "R宇佐美定満", "R上杉謙信"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 174, region: "裏越後", name: "栃尾城", diff: 11, money: 800, food: 160, boss_r: "R", type: "足軽", terrain: "山岳", interference: ["悪天候"], s_cond: "R上杉謙信", s_reward_char: "R上杉謙信",
      cond_desc: "姫武将使用不可", entry_cond: {"type": "gender_count", "value": "female", "count": 0, "op": "<="},
      unique_enemies: ["R斎藤朝信", "R上杉景信", "R甘粕景持", "R柿崎景家"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 175, region: "裏越後", name: "黒滝城", diff: 11, money: 975, food: 195, boss_r: "R", type: "騎馬", terrain: "山岳", interference: ["悪天候"], s_cond: "R上杉謙信", s_reward_char: "R上杉謙信",
      cond_desc: "武田家武将1名以上", entry_cond: {"type": "clan", "value": "武田家", "count": 1, "op": ">="},
      unique_enemies: ["R北条高広", "R本庄繁長", "R上杉謙信"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 176, region: "裏越後", name: "坂戸城", diff: 11, money: 1200, food: 240, boss_r: "SP", type: "足軽", terrain: "城郭", interference: ["布陣失敗"], s_cond: "R上杉景勝", s_reward_char: "R上杉景勝",
      cond_desc: "武田家武将2名以上", entry_cond: {"type": "clan", "value": "武田家", "count": 2, "op": ">="},
      unique_enemies: ["R中条藤資", "R上杉景勝", "R上杉謙信"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 177, region: "裏信濃・甲斐", name: "箕輪城", diff: 11, money: 600, food: 120, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["奇襲"], s_cond: "R長野業正", s_reward_char: "R長野業正",
      cond_desc: "鉄砲1名以下", entry_cond: {"type": "type_count", "value": "鉄砲", "count": 1, "op": "<="},
      unique_enemies: ["R穴山梅雪", "R武田信繁", "R武田勝頼", "R真田幸隆", "R山本勘助", "R武田信玄"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 178, region: "裏信濃・甲斐", name: "戸石城", diff: 11, money: 800, food: 160, boss_r: "R", type: "騎馬", terrain: "山岳", interference: ["奇襲"], s_cond: "R真田幸隆", s_reward_char: "R真田幸隆",
      cond_desc: "鉄砲1名以下", entry_cond: {"type": "type_count", "value": "鉄砲", "count": 1, "op": "<="},
      unique_enemies: ["R高坂昌信", "R内藤昌豊", "R馬場信春", "R山県昌景"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 179, region: "裏信濃・甲斐", name: "海津城", diff: 11, money: 975, food: 195, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["奇襲"], s_cond: "R山本勘助", s_reward_char: "R山本勘助",
      cond_desc: "上杉家武将1名以上", entry_cond: {"type": "clan", "value": "上杉家", "count": 1, "op": ">="},
      unique_enemies: ["R原虎胤", "R小幡虎盛", "R多田満頼", "R横田高松", "R山本勘助"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 180, region: "裏信濃・甲斐", name: "要害山城", diff: 11, money: 1200, food: 240, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["計略"], s_cond: "R武田信玄", s_reward_char: "R武田信玄",
      cond_desc: "上杉家武将2名以上", entry_cond: {"type": "clan", "value": "上杉家", "count": 2, "op": ">="},
      unique_enemies: ["R飯富虎昌", "R甘利虎泰", "R板垣信方", "R諸角虎定", "R武田信玄"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 181, region: "裏三河", name: "一言坂", diff: 12, money: 980, food: 196, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["奇襲", "布陣失敗"], s_cond: "R本多忠勝", s_reward_char: "R本多忠勝",
      cond_desc: "R武将1名以上", entry_cond: {"type": "rarity_count", "value": "R", "count": 1, "op": ">="},
      unique_enemies: ["R服部半蔵", "R榊原康政", "R鳥居元忠", "R井伊直政"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 182, region: "裏三河", name: "二俣城", diff: 12, money: 800, food: 160, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["奇襲", "布陣失敗"], s_cond: "R馬場信春", s_reward_char: "R馬場信春",
      cond_desc: "R武将2名以上", entry_cond: {"type": "rarity_count", "value": "R", "count": 2, "op": ">="},
      unique_enemies: ["R鳥居元忠", "R井伊直政", "R酒井忠次", "R本多忠勝", "SR真田信之", "R榊原康政", "R徳川家康"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 183, region: "裏三河", name: "野田城", diff: 12, money: 700, food: 140, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["奇襲", "布陣失敗"], s_cond: "R武田信玄", s_reward_char: "R武田信玄",
      cond_desc: "R武将3名以上", entry_cond: {"type": "rarity_count", "value": "R", "count": 3, "op": ">="},
      unique_enemies: ["R本多忠勝", "SR本多忠勝", "R徳川家康"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 184, region: "裏安芸・山陽", name: "佐東銀山城", diff: 12, money: 360, food: 72, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["計略"], s_cond: "R毛利元就", s_reward_char: "R毛利元就",
      cond_desc: "C武将1名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 1, "op": ">="},
      unique_enemies: ["R村上武吉", "C清水宗治"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 185, region: "裏安芸・山陽", name: "白鹿城", diff: 12, money: 520, food: 104, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "R毛利元就", s_reward_char: "R毛利元就",
      cond_desc: "C武将1名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 1, "op": ">="},
      unique_enemies: ["C毛利隆元", "C清水宗治", "R吉川元春", "R安国寺恵瓊"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 186, region: "裏安芸・山陽", name: "月山富田城", diff: 12, money: 560, food: 112, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["奇襲"], s_cond: "SR山中鹿之助", s_reward_char: "SR山中鹿之助",
      cond_desc: "C武将2名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 2, "op": ">="},
      unique_enemies: ["R小早川隆景", "C毛利隆元", "R吉川元春", "R毛利元就"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 187, region: "裏安芸・山陽", name: "木津川口", diff: 12, money: 600, food: 120, boss_r: "R", type: "水兵", terrain: "海戦", interference: ["布陣失敗"], s_cond: "R九鬼嘉隆", s_reward_char: "R九鬼嘉隆",
      cond_desc: "C武将2名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 2, "op": ">="},
      unique_enemies: ["R小早川隆景", "R村上武吉", "C乃美宗勝", "SR小早川隆景"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 188, region: "裏安芸・山陽", name: "広島城", diff: 12, money: 800, food: 160, boss_r: "SR", type: "足軽", terrain: "城郭", interference: ["傷病"], s_cond: "R黒田官兵衛", s_reward_char: "SR黒田官兵衛",
      cond_desc: "C武将2名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 2, "op": ">="},
      unique_enemies: ["SR毛利元就", "SR吉川元春"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 189, region: "裏薩摩", name: "岩剣城", diff: 12, money: 510, food: 102, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["計略"], s_cond: "R島津義久", s_reward_char: "R島津義久",
      cond_desc: "SR武将2名以下", entry_cond: {"type": "rarity_count", "value": "SR", "count": 2, "op": "<="},
      unique_enemies: ["C鎌田政年", "R川上久朗", "R島津家久"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 190, region: "裏薩摩", name: "木崎原", diff: 12, money: 710, food: 142, boss_r: "SR", type: "騎馬", terrain: "平原", interference: ["計略"], s_cond: "R島津義弘", s_reward_char: "R島津義弘",
      cond_desc: "SR武将2名以下", entry_cond: {"type": "rarity_count", "value": "SR", "count": 2, "op": "<="},
      unique_enemies: ["C山田有信", "R川上久朗", "R新納忠元", "R島津歳久", "SR島津歳久"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 191, region: "裏薩摩", name: "飯野城", diff: 12, money: 790, food: 158, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["計略", "布陣失敗"], s_cond: "R島津義弘", s_reward_char: "R島津義弘",
      cond_desc: "SR武将1名以下", entry_cond: {"type": "rarity_count", "value": "SR", "count": 1, "op": "<="},
      unique_enemies: ["C鎌田政年", "C山田有信", "R島津家久", "SR島津家久"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 192, region: "裏薩摩", name: "鶴丸城", diff: 12, money: 1100, food: 220, boss_r: "R", type: "鉄砲", terrain: "城郭", interference: ["計略", "布陣失敗"], s_cond: "R島津義弘", s_reward_char: "R島津義弘",
      cond_desc: "SR武将使用不可", entry_cond: {"type": "rarity_count", "value": "SR", "count": 0, "op": "<="},
      unique_enemies: ["R島津義久", "R島津義弘", "R島津歳久", "R島津家久", "SR島津義久"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 193, region: "裏陸奥・出羽", name: "二本松城", diff: 13, money: 750, food: 150, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["悪天候"], s_cond: "R伊達政宗", s_reward_char: "R伊達政宗",
      cond_desc: "伊達家武将2名以上", entry_cond: {"type": "clan", "value": "伊達家", "count": 2, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 194, region: "裏陸奥・出羽", name: "人取橋", diff: 13, money: 880, food: 176, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["悪天候"], s_cond: "R伊達成実", s_reward_char: "R伊達成実",
      cond_desc: "伊達家武将2名以上", entry_cond: {"type": "clan", "value": "伊達家", "count": 2, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 195, region: "裏陸奥・出羽", name: "大崎合戦", diff: 13, money: 900, food: 180, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["悪天候"], s_cond: "R義姫", s_reward_char: "R義姫",
      cond_desc: "伊達家武将2名以上", entry_cond: {"type": "clan", "value": "伊達家", "count": 2, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 196, region: "裏陸奥・出羽", name: "郡山合戦", diff: 13, money: 920, food: 184, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["悪天候", "足止め罠"], s_cond: "R片倉小十郎", s_reward_char: "R片倉小十郎",
      cond_desc: "伊達家武将3名以上", entry_cond: {"type": "clan", "value": "伊達家", "count": 3, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 197, region: "裏陸奥・出羽", name: "黒川城", diff: 13, money: 950, food: 190, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["悪天候", "足止め罠"], s_cond: "R伊達政宗", s_reward_char: "R伊達政宗",
      cond_desc: "伊達家武将3名以上", entry_cond: {"type": "clan", "value": "伊達家", "count": 3, "op": ">="},
      unique_enemies: ["R伊達政宗"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 198, region: "裏上野・武蔵", name: "山中城", diff: 13, money: 585, food: 117, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "R徳川家康", s_reward_char: "R徳川家康",
      cond_desc: "C武将1名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 1, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 199, region: "裏上野・武蔵", name: "韮山城", diff: 13, money: 680, food: 136, boss_r: "R", type: "忍者", terrain: "城郭", interference: ["足止め罠"], s_cond: "R蒲生氏郷", s_reward_char: "R蒲生氏郷",
      cond_desc: "C武将1名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 1, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 200, region: "裏上野・武蔵", name: "松井田城", diff: 13, money: 720, food: 144, boss_r: "R", type: "忍者", terrain: "城郭", interference: ["足止め罠"], s_cond: "R真田昌幸", s_reward_char: "R真田昌幸",
      cond_desc: "C武将2名以上", entry_cond: {"type": "rarity_count", "value": "C", "count": 2, "op": ">="},
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 201, region: "裏上野・武蔵", name: "忍城", diff: 13, money: 570, food: 114, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "R石田三成", s_reward_char: "R石田三成",
      cond_desc: "豊臣家武将2名以上", entry_cond: {"type": "clan", "value": "豊臣家", "count": 2, "op": ">="},
      unique_enemies: ["R甲斐姫", "R成田長親"],
      random_rewards: [{"type": "money", "val": 180}, {"type": "char", "name": "R成田長親", "weight": 5}] },
    { id: 202, region: "裏上野・武蔵", name: "裏小田原城", diff: 13, money: 4500, food: 900, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "UR豊太閤秀吉", s_reward_char: "UR豊太閤秀吉",
      cond_desc: "豊臣家武将3名以上", entry_cond: {"type": "clan", "value": "豊臣家", "count": 3, "op": ">="},
      unique_enemies: ["R北条氏康", "R北条氏政", "R北条氏邦", "R北条綱成", "SR北条氏康", "SR風魔小太郎"],
      random_rewards: [{"type": "money", "val": 210}, {"type": "char", "name": "SR風魔小太郎", "weight": 5}] },
    { id: 203, region: "裏信濃・甲斐", name: "箕輪城", diff: 11, money: 600, food: 120, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["奇襲"], s_cond: "R長野業正", s_reward_char: "R長野業正",
      cond_desc: "鉄砲1名以下", entry_cond: {"type": "type_count", "value": "鉄砲", "count": 1, "op": "<="},
      unique_enemies: ["R穴山梅雪", "R武田信繁", "R武田勝頼", "R真田幸隆", "R山本勘助", "R武田信玄"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 204, region: "裏信濃・甲斐", name: "戸石城", diff: 11, money: 800, food: 160, boss_r: "R", type: "騎馬", terrain: "山岳", interference: ["奇襲"], s_cond: "R真田幸隆", s_reward_char: "R真田幸隆",
      cond_desc: "鉄砲1名以下", entry_cond: {"type": "type_count", "value": "鉄砲", "count": 1, "op": "<="},
      unique_enemies: ["R高坂昌信", "R内藤昌豊", "R馬場信春", "R山県昌景"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 205, region: "裏信濃・甲斐", name: "海津城", diff: 11, money: 975, food: 195, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["奇襲"], s_cond: "R山本勘助", s_reward_char: "R山本勘助",
      cond_desc: "上杉家武将1名以上", entry_cond: {"type": "clan", "value": "上杉家", "count": 1, "op": ">="},
      unique_enemies: ["R原虎胤", "R小幡虎盛", "R多田満頼", "R横田高松", "R山本勘助"],
      random_rewards: [{"type": "money", "val": 120}] },
    { id: 206, region: "裏信濃・甲斐", name: "要害山城", diff: 11, money: 1200, food: 240, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["計略"], s_cond: "R武田信玄", s_reward_char: "R武田信玄",
      cond_desc: "上杉家武将2名以上", entry_cond: {"type": "clan", "value": "上杉家", "count": 2, "op": ">="},
      unique_enemies: ["R飯富虎昌", "R甘利虎泰", "R板垣信方", "R諸角虎定", "R武田信玄"],
      random_rewards: [{"type": "money", "val": 150}] },
    { id: 207, region: "裏摂津・備前", name: "降露坂", diff: 15, money: 1200, food: 151, boss_r: "SR", type: "足軽", terrain: "山岳", interference: ["悪天候", "計略"], s_cond: "R尼子晴久", s_reward_char: "R尼子晴久",
      cond_desc: "毛利家武将2名以上", entry_cond: {"type": "clan", "value": "毛利家", "count": 2, "op": ">="},
      unique_enemies: ["R尼子経久", "SR山中鹿之助"],
      random_rewards: [{"type": "money", "val": 240}] },
    { id: 208, region: "裏摂津・備前", name: "花隈城", diff: 15, money: 1050, food: 100, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["奇襲", "計略"], s_cond: "R池田恒興", s_reward_char: "R池田恒興",
      cond_desc: "兵糧合計300以下", entry_cond: {"type": "total_cost", "value": 300, "op": "<="},
      unique_enemies: ["R荒木村重"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 209, region: "裏摂津・備前", name: "姫路城", diff: 15, money: 1200, food: 173, boss_r: "SR", type: "鉄砲", terrain: "城郭", interference: ["傷病", "足止め罠", "計略"], s_cond: "R黒田官兵衛", s_reward_char: "R黒田官兵衛",
      cond_desc: "豊臣家武将2名以上", entry_cond: {"type": "clan", "value": "豊臣家", "count": 2, "op": ">="},
      unique_enemies: ["R黒田官兵衛", "R後藤又兵衛"],
      random_rewards: [{"type": "money", "val": 240}] },
    { id: 210, region: "裏土佐・南海", name: "十河城", diff: 13, money: 900, food: 144, boss_r: "SR", type: "水兵", terrain: "城郭", interference: ["奇襲", "傷病", "悪天候", "布陣失敗", "足止め罠", "計略"], s_cond: "C仙石久秀", s_reward_char: "C仙石久秀",
      cond_desc: "長宗我部家武将2名以上", entry_cond: {"type": "clan", "value": "長宗我部家", "count": 2, "op": ">="},
      unique_enemies: ["SR十河一存"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 211, region: "裏土佐・南海", name: "夷山城", diff: 13, money: 900, food: 144, boss_r: "R", type: "水兵", terrain: "城郭", interference: ["奇襲", "傷病", "悪天候", "布陣失敗", "足止め罠", "計略"], s_cond: "R長宗我部信親", s_reward_char: "R長宗我部信親",
      cond_desc: "豊臣家武将2名以上", entry_cond: {"type": "clan", "value": "豊臣家", "count": 2, "op": ">="},
      unique_enemies: ["R福留儀重", "C吉良親貞", "R吉田重俊"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 212, region: "裏土佐・南海", name: "勝瑞城", diff: 13, money: 900, food: 144, boss_r: "R", type: "水兵", terrain: "城郭", interference: ["奇襲", "傷病", "悪天候", "布陣失敗", "足止め罠", "計略"], s_cond: "R長宗我部元親", s_reward_char: "R長宗我部元親",
      cond_desc: "長宗我部家武将2名以上", entry_cond: {"type": "clan", "value": "長宗我部家", "count": 2, "op": ">="},
      unique_enemies: ["R香宗我部親泰"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 213, region: "裏土佐・南海", name: "中富川", diff: 13, money: 900, food: 144, boss_r: "R", type: "水兵", terrain: "河川", interference: ["奇襲", "傷病", "悪天候", "布陣失敗", "足止め罠", "計略"], s_cond: "R長宗我部元親", s_reward_char: "R長宗我部元親",
      cond_desc: "水兵3名以上", entry_cond: {"type": "type_count", "value": "水兵", "count": 3, "op": ">="},
      unique_enemies: ["R長宗我部信親"],
      random_rewards: [{"type": "money", "val": 180}] },
    { id: 214, region: "裏土佐・南海", name: "黒瀬城", diff: 13, money: 1050, food: 144, boss_r: "R", type: "水兵", terrain: "城郭", interference: ["布陣失敗"], s_cond: "UR豊太閤秀吉", s_reward_char: "UR豊太閤秀吉",
      cond_desc: "豊臣家武将3名以上", entry_cond: {"type": "clan", "value": "豊臣家", "count": 3, "op": ">="},
      unique_enemies: ["R西園寺公広"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 215, region: "裏肥前・肥後", name: "柳川城", diff: 14, money: 1050, food: 149, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["奇襲"], s_cond: "R鍋島直茂", s_reward_char: "R鍋島直茂",
      cond_desc: "龍造寺家武将3名以上", entry_cond: {"type": "clan", "value": "龍造寺家", "count": 3, "op": ">="},
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 216, region: "裏肥前・肥後", name: "城村城", diff: 14, money: 1050, food: 167, boss_r: "R", type: "騎馬", terrain: "平原", interference: ["布陣失敗", "計略"], s_cond: "SSR立花宗茂", s_reward_char: "SSR立花宗茂",
      cond_desc: "兵数合計3000以上", entry_cond: {"type": "hp", "value": 3000, "op": ">="},
      unique_enemies: ["R成松信勝", "R百武賢兼"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 217, region: "裏肥前・肥後", name: "田中城", diff: 14, money: 1050, food: 174, boss_r: "R", type: "騎馬", terrain: "城郭", interference: ["布陣失敗", "計略"], s_cond: "R安国寺恵瓊", s_reward_char: "R安国寺恵瓊",
      cond_desc: "兵数合計4000以上", entry_cond: {"type": "hp", "value": 4000, "op": ">="},
      unique_enemies: ["R江里口信常", "R円城寺信胤", "R木下昌直"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 218, region: "裏肥前・肥後", name: "隈本城", diff: 14, money: 1200, food: 244, boss_r: "SR", type: "足軽", terrain: "城郭", interference: ["奇襲", "傷病", "悪天候", "布陣失敗", "足止め罠", "計略"], s_cond: "R佐々成政", s_reward_char: "R佐々成政",
      cond_desc: "兵数合計5000以上", entry_cond: {"type": "hp", "value": 5000, "op": ">="},
      unique_enemies: ["R龍造寺隆信", "R鍋島直茂"],
      random_rewards: [{"type": "money", "val": 240}] },
    { id: 219, region: "裏豊前・豊後", name: "二階崩れの変", diff: 14, money: 1050, food: 111, boss_r: "C", type: "足軽", terrain: "城郭", interference: ["足止め罠"], s_cond: "C大友宗麟", s_reward_char: "C大友宗麟",
      cond_desc: "兵数合計1000以下", entry_cond: {"type": "hp", "value": 1000, "op": "<="},
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 220, region: "裏豊前・豊後", name: "岩屋城", diff: 14, money: 1050, food: 153, boss_r: "R", type: "足軽", terrain: "城郭", interference: ["布陣失敗", "奇襲"], s_cond: "R島津貴久", s_reward_char: "R島津貴久",
      cond_desc: "島津家武将3名以上", entry_cond: {"type": "clan", "value": "島津家", "count": 3, "op": ">="},
      unique_enemies: ["R高橋紹運"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 221, region: "裏豊前・豊後", name: "門司城", diff: 14, money: 1050, food: 190, boss_r: "R", type: "水兵", terrain: "海戦", interference: ["傷病", "悪天候"], s_cond: "R小早川隆景", s_reward_char: "R小早川隆景",
      cond_desc: "毛利家武将3名以上", entry_cond: {"type": "clan", "value": "毛利家", "count": 3, "op": ">="},
      unique_enemies: ["R立花道雪", "R高橋紹運"],
      random_rewards: [{"type": "money", "val": 210}] },
    { id: 222, region: "裏豊前・豊後", name: "立花山城", diff: 14, money: 1200, food: 226, boss_r: "SR", type: "足軽", terrain: "城郭", interference: ["奇襲", "傷病", "悪天候", "布陣失敗", "足止め罠", "計略"], s_cond: "R島津義久", s_reward_char: "R島津義久",
      cond_desc: "島津家武将1名以上", entry_cond: {"type": "clan", "value": "島津家", "count": 1, "op": ">="},
      unique_enemies: ["SR立花誾千代", "SSR立花宗茂", "R立花道雪"],
      random_rewards: [{"type": "money", "val": 240}] }
];